apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_USERNAME: anV0aW9uY2s=      # Base64-encoded 'jutionck'
  DB_PASSWORD: cGFzc3dvcmQ=      # Base64-encoded 'password'
  JWT_SECRET: NDA0RTYzNTI2NTU2NkE1ODZFMzI3MjM1NzUzODc4MmY0MTNGNDQyODQ3MkI0QjYyNTA2NTY2Qjk1OTcw  # Base64-encoded JWT secret key
  ADMIN_PASSWORD: cGFzc3dvcmQ=   # Base64-encoded password untuk akun admin
